In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Create made up regression dataset
X, y = make_regression(n_samples=100, n_features=20, noise=0.95)
# Create a table to view it
df = pd.DataFrame(X)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-0.461439,0.356490,-0.616846,-0.083224,-0.455538,1.103417,-0.150664,1.048124,-0.886119,2.029727,0.350194,-2.441865,0.250404,0.660307,-1.131061,-0.426756,0.076821,-0.062659,-0.710543,-0.633332
1,0.921371,-0.493525,0.620176,0.981565,0.594101,0.163350,0.673761,0.519658,-1.724286,1.805244,-1.923020,-0.475378,0.605160,0.364475,1.495929,0.285262,0.187402,-0.893084,0.772634,1.317015
2,1.014592,0.194224,-0.319118,-0.347238,2.133307,1.898256,-0.896060,-1.976766,-0.922422,-2.143012,1.147059,-0.024244,-0.244425,0.476380,-0.356286,0.312562,2.697580,-0.674254,1.390185,0.004929
3,1.661893,0.177789,1.969780,0.933236,-0.345494,1.491930,1.206125,0.403850,-0.057921,0.001319,0.656485,-1.007817,0.617553,-0.891220,0.156292,-0.605600,0.594810,-0.061752,2.031318,0.798951
4,1.564431,-0.064563,0.486923,-0.220924,-0.950054,-0.291044,-1.023296,-0.182787,-0.904486,-0.545738,0.777476,0.379599,1.027422,0.373570,-0.868907,0.434352,0.048623,1.072863,-1.290531,0.433957

In [2]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Create made up regression dataset
X, y = make_regression(n_samples=100, n_features=20, noise=0.95)
# Create a table to view it
df = pd.DataFrame(X)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.469186,0.686717,-0.734231,1.252761,0.171993,1.416255,-0.553692,-0.738777,-2.194780,-0.863054,-0.056576,-1.115262,-0.462613,0.675785,0.446846,-0.134511,2.122995,-0.996794,-1.299782,-0.836320
1,1.479947,-1.052061,-0.741371,-1.048619,0.613415,0.093664,0.829920,1.701824,0.037249,1.179430,0.581132,-0.303176,-0.551426,1.117779,0.173363,0.262446,0.784696,0.922093,-0.775755,-0.180095
2,-0.309289,-1.760375,1.020313,0.642142,0.177427,1.468737,-0.931536,0.975487,-1.082853,-2.402272,0.043138,0.613207,0.110518,-0.478009,0.318320,0.211121,0.647067,0.447678,-0.557319,0.262618
3,-0.826984,2.494946,-0.080824,-0.851164,-1.154204,-0.038736,0.093839,-2.065093,-0.067368,-0.724164,1.047785,-0.962256,-0.471782,-1.377163,-1.201960,-1.011009,0.254373,-0.964562,-0.604008,2.734248
4,-0.410231,-1.240217,-2.089089,0.045382,0.590409,-0.773899,-0.579029,0.873337,1.163399,0.106454,-0.714127,0.877397,-0.126823,-0.826484,0.782013,-0.790336,1.044605,0.041423,-1.303683,-1.185027

In [3]:
# Create the dataset once again. This time, introduce high
# multicollinearity by setting low rank to the input matrix
X, y = make_regression(n_samples=100, n_features=20, noise=0.95, effective_rank=1)
df = pd.DataFrame(X)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.001570,0.027865,-0.015801,-0.007921,-0.064434,-0.019933,0.005485,-0.003994,-0.020156,0.007031,0.009243,-0.020989,0.019355,-0.050526,-0.017593,0.041065,0.055037,0.002753,0.013150,-0.034026
1,-0.011262,-0.082026,0.044121,-0.019031,0.030696,-0.015017,-0.035542,0.002843,-0.018486,-0.000699,0.025718,-0.052752,-0.028055,0.036601,0.043223,-0.040938,-0.034051,-0.055729,-0.017754,0.024080
2,0.035564,-0.010717,-0.043791,-0.023855,-0.010605,0.036523,0.018063,0.007785,-0.002427,-0.012026,0.000588,-0.011834,-0.003260,-0.039444,-0.060425,0.017025,-0.004104,0.063664,-0.021202,0.054273
3,-0.052209,0.015204,0.001323,0.003288,0.009011,0.015812,-0.045141,-0.005155,-0.055163,-0.016234,0.029011,0.015112,0.003297,-0.048370,-0.009821,0.015680,0.048898,0.021951,0.017714,0.000548
4,-0.029978,-0.038142,0.002783,0.008174,0.078207,-0.021001,-0.046288,0.000180,-0.008864,-0.009367,-0.004067,0.032542,-0.046561,0.005999,-0.006440,-0.029179,-0.024673,0.022895,-0.033107,0.033451

In [4]:
# Cross Validation will fit the classifier N number of times
# and display the accuracies
cv = cross_val_score(LinearRegression(), X, y, cv=10)
print("Mean: {}".format(cv.mean()))
print("Values: {}".format(cv))

Mean: 0.8840134159275743
Values: [0.8819681  0.70561503 0.93114928 0.92110419 0.8822474  0.95937661
 0.95115923 0.80489292 0.86238791 0.94023349]