In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset = pd.read_csv("https://raw.githubusercontent.com/benvictoria17/MachineLearning/master/dataset/Video%20Game%20Sales%20with%20Ratings/Video_Games_Sales_as_at_22_Dec_2016.csv")
dataset.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object
 15  Rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [4]:
dataset = dataset.drop('Other_Sales', axis = 1) # apaga a coluna
dataset = dataset.drop('Global_Sales', axis = 1) # apaga a coluna
dataset = dataset.drop('Developer', axis = 1) # apaga a coluna
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   Critic_Count     8137 non-null   float64
 10  User_Score       10015 non-null  object
 11  User_Count       7590 non-null   float64
 12  Rating           9950 non-null   object
dtypes: float64(7), object(6)
memory usage: 1.7+ MB

In [5]:
dataset = dataset.dropna(axis = 0) # apagar por linha
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6825 entries, 0 to 16706
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6825 non-null   object
 1   Platform         6825 non-null   object
 2   Year_of_Release  6825 non-null   float64
 3   Genre            6825 non-null   object
 4   Publisher        6825 non-null   object
 5   NA_Sales         6825 non-null   float64
 6   EU_Sales         6825 non-null   float64
 7   JP_Sales         6825 non-null   float64
 8   Critic_Score     6825 non-null   float64
 9   Critic_Count     6825 non-null   float64
 10  User_Score       6825 non-null   object
 11  User_Count       6825 non-null   float64
 12  Rating           6825 non-null   object
dtypes: float64(7), object(6)
memory usage: 746.5+ KB

In [6]:
valores_menores_1 = dataset.loc[dataset['NA_Sales'] < 1]
valores_menores_1.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Rating
85,The Sims 3,PC,2009.0,Simulation,Electronic Arts,0.99,6.42,0.00,86.0,75.0,7.6,886.0,T
94,FIFA 17,PS4,2016.0,Sports,Electronic Arts,0.66,5.75,0.08,85.0,41.0,5,398.0,E
126,FIFA 14,PS3,2013.0,Sports,Electronic Arts,0.78,4.24,0.07,86.0,37.0,4.3,576.0,E
138,World of Warcraft,PC,2004.0,Role-Playing,Activision,0.08,6.21,0.00,93.0,57.0,7.3,2182.0,T
143,FIFA 15,PS4,2014.0,Sports,Electronic Arts,0.80,4.33,0.05,82.0,47.0,5.7,988.0,E

In [7]:
dataset = dataset.loc[dataset['NA_Sales'] > 1]
dataset = dataset.loc[dataset['EU_Sales'] > 1]
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 0 to 636
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             258 non-null    object
 1   Platform         258 non-null    object
 2   Year_of_Release  258 non-null    float64
 3   Genre            258 non-null    object
 4   Publisher        258 non-null    object
 5   NA_Sales         258 non-null    float64
 6   EU_Sales         258 non-null    float64
 7   JP_Sales         258 non-null    float64
 8   Critic_Score     258 non-null    float64
 9   Critic_Count     258 non-null    float64
 10  User_Score       258 non-null    object
 11  User_Count       258 non-null    float64
 12  Rating           258 non-null    object
dtypes: float64(7), object(6)
memory usage: 28.2+ KB

In [8]:
nome_jogos = dataset['Name']
dataset = dataset.drop('Name', axis = 1) # Assim, vamos diminuir a variedade de dados
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 258 entries, 0 to 636
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Platform         258 non-null    object
 1   Year_of_Release  258 non-null    float64
 2   Genre            258 non-null    object
 3   Publisher        258 non-null    object
 4   NA_Sales         258 non-null    float64
 5   EU_Sales         258 non-null    float64
 6   JP_Sales         258 non-null    float64
 7   Critic_Score     258 non-null    float64
 8   Critic_Count     258 non-null    float64
 9   User_Score       258 non-null    object
 10  User_Count       258 non-null    float64
 11  Rating           258 non-null    object
dtypes: float64(7), object(5)
memory usage: 26.2+ KB

In [9]:
from keras.layers import Dense, Dropout, Activation, Input
from keras.models import Model
previsores = dataset.iloc[:, [0,1,2,3,7,8,9,10,11]].values
previsores

array([['Wii', 2006.0, 'Sports', ..., '8', 322.0, 'E'],
       ['Wii', 2008.0, 'Racing', ..., '8.3', 709.0, 'E'],
       ['Wii', 2009.0, 'Sports', ..., '8', 192.0, 'E'],
       ...,
       ['Wii', 2007.0, 'Sports', ..., '8', 124.0, 'E10+'],
       ['PS2', 2001.0, 'Racing', ..., '7.9', 46.0, 'T'],
       ['PS2', 2003.0, 'Simulation', ..., '8.4', 42.0, 'T']], dtype=object)

In [10]:
vendas_na = dataset.iloc[:, 4].values
vendas_eu = dataset.iloc[:, 5].values
vendas_jp = dataset.iloc[:, 6].values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
# Transformar colunas categóricas em numéricas

labelEncoder = LabelEncoder()

previsores[:, 0] = labelEncoder.fit_transform(previsores[:, 0]);
previsores[:, 2] = labelEncoder.fit_transform(previsores[:, 2]);
previsores[:, 3] = labelEncoder.fit_transform(previsores[:, 3]);
previsores[:, 8] = labelEncoder.fit_transform(previsores[:, 8]);
previsores

array([[10, 2006.0, 10, ..., '8', 322.0, 0],
       [10, 2008.0, 6, ..., '8.3', 709.0, 0],
       [10, 2009.0, 10, ..., '8', 192.0, 0],
       ...,
       [10, 2007.0, 10, ..., '8', 124.0, 1],
       [6, 2001.0, 6, ..., '7.9', 46.0, 3],
       [6, 2003.0, 9, ..., '8.4', 42.0, 3]], dtype=object)

In [11]:

column_transform = ColumnTransformer([("encoder", 
                         OneHotEncoder(), 
                        [0,2,3,8])],    
                       remainder = 'passthrough')


previsores = column_transform.fit_transform(previsores).toarray()
previsores

array([[  0. ,   0. ,   0. , ...,  51. ,   8. , 322. ],
       [  0. ,   0. ,   0. , ...,  73. ,   8.3, 709. ],
       [  0. ,   0. ,   0. , ...,  73. ,   8. , 192. ],
       ...,
       [  0. ,   0. ,   0. , ...,  47. ,   8. , 124. ],
       [  0. ,   0. ,   0. , ...,  15. ,   7.9,  46. ],
       [  0. ,   0. ,   0. , ...,  26. ,   8.4,  42. ]])

In [13]:
previsores.shape

(258, 61)

In [14]:
quantidade_saida = 3
quantidade_entrada = previsores.shape[1]
units = (quantidade_entrada + quantidade_saida) / 2
units

32.0

In [15]:

camada_entrada = Input(shape=(61,))

camada_oculta_1 = Dense(units = units, activation = 'sigmoid')(camada_entrada) # ligação entre as camadas
camada_oculta_2 = Dense(units = units, activation = 'sigmoid')(camada_oculta_1)

# Previsão de três saídas para as três regiões previstas
camada_saida_1 = Dense(units = 1, activation = 'linear')(camada_oculta_2)
camada_saida_2 = Dense(units = 1, activation = 'linear')(camada_oculta_2)
camada_saida_3 = Dense(units = 1, activation = 'linear')(camada_oculta_2)

regressor = Model(inputs = camada_entrada, 
                  outputs = [camada_saida_1, camada_saida_2, camada_saida_3])

regressor.compile(optimizer = 'adam', loss = 'mse')

regressor.fit(previsores, [vendas_na, vendas_eu, vendas_jp],
             epochs = 50, batch_size = 100)

Epoch 1/50
3/3 [==============================] - 0s 1ms/step - loss: 37.1314 - dense_2_loss: 25.0796 - dense_3_loss: 10.4792 - dense_4_loss: 1.5726
Epoch 2/50
3/3 [==============================] - 0s 1ms/step - loss: 36.0193 - dense_2_loss: 24.3564 - dense_3_loss: 10.1703 - dense_4_loss: 1.4926
Epoch 3/50
3/3 [==============================] - 0s 1ms/step - loss: 34.8800 - dense_2_loss: 23.5779 - dense_3_loss: 9.8718 - dense_4_loss: 1.4303
Epoch 4/50
3/3 [==============================] - 0s 2ms/step - loss: 33.8611 - dense_2_loss: 22.8887 - dense_3_loss: 9.5984 - dense_4_loss: 1.3739
Epoch 5/50
3/3 [==============================] - 0s 1ms/step - loss: 32.9264 - dense_2_loss: 22.2525 - dense_3_loss: 9.3472 - dense_4_loss: 1.3267
Epoch 6/50
3/3 [==============================] - 0s 2ms/step - loss: 31.9999 - dense_2_loss: 21.6107 - dense_3_loss: 9.0980 - dense_4_loss: 1.2912
Epoch 7/50
3/3 [==============================] - 0s 2ms/step - loss: 31.1326 - dense_2_loss: 21.0106 - dense_3_loss: 8.8643 - dense_4_loss: 1.2577
Epoch 8/50
3/3 [==============================] - 0s 2ms/step - loss: 30.3354 - dense_2_loss: 20.4497 - dense_3_loss: 8.6564 - dense_4_loss: 1.2293
Epoch 9/50
3/3 [==============================] - 0s 2ms/step - loss: 29.5454 - dense_2_loss: 19.8860 - dense_3_loss: 8.4516 - dense_4_loss: 1.2078
Epoch 10/50
3/3 [==============================] - 0s 2ms/step - loss: 28.8007 - dense_2_loss: 19.3500 - dense_3_loss: 8.2602 - dense_4_loss: 1.1905
Epoch 11/50
3/3 [==============================] - 0s 1ms/step - loss: 28.1390 - dense_2_loss: 18.8649 - dense_3_loss: 8.0927 - dense_4_loss: 1.1814
Epoch 12/50
3/3 [==============================] - 0s 2ms/step - loss: 27.5065 - dense_2_loss: 18.4039 - dense_3_loss: 7.9294 - dense_4_loss: 1.1732
Epoch 13/50
3/3 [==============================] - 0s 1ms/step - loss: 26.8589 - dense_2_loss: 17.9345 - dense_3_loss: 7.7564 - dense_4_loss: 1.1680
Epoch 14/50
3/3 [==============================] - 0s 2ms/step - loss: 26.2637 - dense_2_loss: 17.4977 - dense_3_loss: 7.6002 - dense_4_loss: 1.1658
Epoch 15/50
3/3 [==============================] - 0s 1ms/step - loss: 25.7269 - dense_2_loss: 17.1004 - dense_3_loss: 7.4629 - dense_4_loss: 1.1635
Epoch 16/50
3/3 [==============================] - 0s 2ms/step - loss: 25.2081 - dense_2_loss: 16.7062 - dense_3_loss: 7.3381 - dense_4_loss: 1.1639
Epoch 17/50
3/3 [==============================] - 0s 2ms/step - loss: 24.7016 - dense_2_loss: 16.3209 - dense_3_loss: 7.2180 - dense_4_loss: 1.1627
Epoch 18/50
3/3 [==============================] - 0s 2ms/step - loss: 24.2371 - dense_2_loss: 15.9779 - dense_3_loss: 7.0975 - dense_4_loss: 1.1616
Epoch 19/50
3/3 [==============================] - 0s 1ms/step - loss: 23.8095 - dense_2_loss: 15.6569 - dense_3_loss: 6.9906 - dense_4_loss: 1.1620
Epoch 20/50
3/3 [==============================] - 0s 1ms/step - loss: 23.4006 - dense_2_loss: 15.3508 - dense_3_loss: 6.8886 - dense_4_loss: 1.1612
Epoch 21/50
3/3 [==============================] - 0s 2ms/step - loss: 23.0191 - dense_2_loss: 15.0729 - dense_3_loss: 6.7854 - dense_4_loss: 1.1608
Epoch 22/50
3/3 [==============================] - 0s 1ms/step - loss: 22.6688 - dense_2_loss: 14.8134 - dense_3_loss: 6.6952 - dense_4_loss: 1.1602
Epoch 23/50
3/3 [==============================] - 0s 2ms/step - loss: 22.3558 - dense_2_loss: 14.5837 - dense_3_loss: 6.6121 - dense_4_loss: 1.1600
Epoch 24/50
3/3 [==============================] - 0s 2ms/step - loss: 22.0279 - dense_2_loss: 14.3335 - dense_3_loss: 6.5350 - dense_4_loss: 1.1594
Epoch 25/50
3/3 [==============================] - 0s 2ms/step - loss: 21.7382 - dense_2_loss: 14.1207 - dense_3_loss: 6.4587 - dense_4_loss: 1.1587
Epoch 26/50
3/3 [==============================] - 0s 2ms/step - loss: 21.4906 - dense_2_loss: 13.9369 - dense_3_loss: 6.3965 - dense_4_loss: 1.1572
Epoch 27/50
3/3 [==============================] - 0s 1ms/step - loss: 21.2328 - dense_2_loss: 13.7433 - dense_3_loss: 6.3328 - dense_4_loss: 1.1567
Epoch 28/50
3/3 [==============================] - 0s 1ms/step - loss: 21.0061 - dense_2_loss: 13.5711 - dense_3_loss: 6.2799 - dense_4_loss: 1.1551
Epoch 29/50
3/3 [==============================] - 0s 1ms/step - loss: 20.7758 - dense_2_loss: 13.3985 - dense_3_loss: 6.2232 - dense_4_loss: 1.1541
Epoch 30/50
3/3 [==============================] - 0s 1ms/step - loss: 20.5918 - dense_2_loss: 13.2575 - dense_3_loss: 6.1799 - dense_4_loss: 1.1544
Epoch 31/50
3/3 [==============================] - 0s 1ms/step - loss: 20.4164 - dense_2_loss: 13.1220 - dense_3_loss: 6.1407 - dense_4_loss: 1.1538
Epoch 32/50
3/3 [==============================] - 0s 2ms/step - loss: 20.2624 - dense_2_loss: 13.0034 - dense_3_loss: 6.1063 - dense_4_loss: 1.1526
Epoch 33/50
3/3 [==============================] - 0s 1ms/step - loss: 20.1069 - dense_2_loss: 12.8806 - dense_3_loss: 6.0739 - dense_4_loss: 1.1524
Epoch 34/50
3/3 [==============================] - 0s 2ms/step - loss: 19.9873 - dense_2_loss: 12.7851 - dense_3_loss: 6.0492 - dense_4_loss: 1.1530
Epoch 35/50
3/3 [==============================] - 0s 2ms/step - loss: 19.8652 - dense_2_loss: 12.6886 - dense_3_loss: 6.0233 - dense_4_loss: 1.1533
Epoch 36/50
3/3 [==============================] - 0s 2ms/step - loss: 19.7455 - dense_2_loss: 12.5954 - dense_3_loss: 5.9978 - dense_4_loss: 1.1524
Epoch 37/50
3/3 [==============================] - 0s 2ms/step - loss: 19.6474 - dense_2_loss: 12.5215 - dense_3_loss: 5.9744 - dense_4_loss: 1.1515
Epoch 38/50
3/3 [==============================] - 0s 2ms/step - loss: 19.5727 - dense_2_loss: 12.4600 - dense_3_loss: 5.9616 - dense_4_loss: 1.1511
Epoch 39/50
3/3 [==============================] - 0s 3ms/step - loss: 19.4726 - dense_2_loss: 12.3787 - dense_3_loss: 5.9434 - dense_4_loss: 1.1505
Epoch 40/50
3/3 [==============================] - 0s 4ms/step - loss: 19.4233 - dense_2_loss: 12.3383 - dense_3_loss: 5.9354 - dense_4_loss: 1.1496
Epoch 41/50
3/3 [==============================] - 0s 2ms/step - loss: 19.3541 - dense_2_loss: 12.2818 - dense_3_loss: 5.9231 - dense_4_loss: 1.1492
Epoch 42/50
3/3 [==============================] - 0s 2ms/step - loss: 19.3152 - dense_2_loss: 12.2488 - dense_3_loss: 5.9176 - dense_4_loss: 1.1488
Epoch 43/50
3/3 [==============================] - 0s 1ms/step - loss: 19.2629 - dense_2_loss: 12.2053 - dense_3_loss: 5.9091 - dense_4_loss: 1.1485
Epoch 44/50
3/3 [==============================] - 0s 2ms/step - loss: 19.2171 - dense_2_loss: 12.1673 - dense_3_loss: 5.9014 - dense_4_loss: 1.1484
Epoch 45/50
3/3 [==============================] - 0s 1ms/step - loss: 19.1764 - dense_2_loss: 12.1334 - dense_3_loss: 5.8950 - dense_4_loss: 1.1480
Epoch 46/50
3/3 [==============================] - 0s 2ms/step - loss: 19.1477 - dense_2_loss: 12.1093 - dense_3_loss: 5.8904 - dense_4_loss: 1.1480
Epoch 47/50
3/3 [==============================] - 0s 2ms/step - loss: 19.1235 - dense_2_loss: 12.0877 - dense_3_loss: 5.8878 - dense_4_loss: 1.1480
Epoch 48/50
3/3 [==============================] - 0s 2ms/step - loss: 19.0921 - dense_2_loss: 12.0617 - dense_3_loss: 5.8826 - dense_4_loss: 1.1477
Epoch 49/50
3/3 [==============================] - 0s 2ms/step - loss: 19.0772 - dense_2_loss: 12.0479 - dense_3_loss: 5.8821 - dense_4_loss: 1.1472
Epoch 50/50
3/3 [==============================] - 0s 1ms/step - loss: 19.0555 - dense_2_loss: 12.0295 - dense_3_loss: 5.8792 - dense_4_loss: 1.1469

In [16]:
previsao_na, previsao_eu, previsao_jp = regressor.predict(previsores)
previsao_na[0:10]

array([[2.9441476],
       [2.9199512],
       [2.9441476],
       [2.9441476],
       [2.9441476],
       [2.9441473],
       [2.9441476],
       [2.9441476],
       [2.9441476],
       [2.9441476]], dtype=float32)

In [17]:
vendas_na[0:10]

array([41.36, 15.68, 15.61, 11.28, 13.96, 14.44,  9.71,  8.92, 15.  ,
        9.01])

In [18]:
features_final = np.column_stack((nome_jogos, vendas_na, previsao_na, vendas_eu, previsao_eu, vendas_jp, previsao_jp))
features_final

array([['Wii Sports', 41.36, 2.9441475868225098, ..., 2.2526893615722656,
        3.77, 0.656384289264679],
       ['Mario Kart Wii', 15.68, 2.9199512004852295, ...,
        2.2574777603149414, 3.79, 0.5935144424438477],
       ['Wii Sports Resort', 15.61, 2.9441475868225098, ...,
        2.2526893615722656, 3.28, 0.656384289264679],
       ...,
       ['Mario Strikers Charged', 1.05, 2.9441475868225098, ...,
        2.2526891231536865, 0.24, 0.6563843488693237],
       ['Crazy Taxi', 1.13, 2.9441475868225098, ..., 2.2526891231536865,
        0.06, 0.6563843488693237],
       ["The Sims: Bustin' Out", 1.07, 2.9441475868225098, ...,
        2.2526891231536865, 0.0, 0.6563843488693237]], dtype=object)

In [20]:
dataset_previsao = pd.DataFrame(data = features_final, 
                                columns = ['Names', 
                                           'NA_Sales',
                                           'NA_Sales_Predict',
                                           'EU_Sales',
                                           'EU_Sales_Predict',
                                           'JP_Sales',
                                           'JP_Sales_Predict'])
dataset_previsao.head(20)

,Names,NA_Sales,NA_Sales_Predict,EU_Sales,EU_Sales_Predict,JP_Sales,JP_Sales_Predict
0,Wii Sports,41.36,2.94415,28.96,2.25269,3.77,0.656384
1,Mario Kart Wii,15.68,2.91995,12.76,2.25748,3.79,0.593514
2,Wii Sports Resort,15.61,2.94415,10.93,2.25269,3.28,0.656384
3,New Super Mario Bros.,11.28,2.94415,9.14,2.25269,6.5,0.656384
4,Wii Play,13.96,2.94415,9.18,2.25269,2.93,0.656384
5,New Super Mario Bros. Wii,14.44,2.94415,6.94,2.25269,4.7,0.656384
6,Mario Kart DS,9.71,2.94415,7.47,2.25269,4.13,0.656384
7,Wii Fit,8.92,2.94415,8.03,2.25269,3.6,0.656384
8,Kinect Adventures!,15,2.94415,4.89,2.25269,0.24,0.656384
9,Wii Fit Plus,9.01,2.94415,8.49,2.25269,2.53,0.656384
10,Grand Theft Auto V,7.02,3.03644,9.09,2.2287,0.98,0.539235
11,Brain Age: Train Your Brain in Minutes a Day,4.74,2.94415,9.2,2.25269,4.16,0.656384
12,Grand Theft Auto V,9.66,3.03644,5.14,2.2287,0.06,0.539235
13,Grand Theft Auto: Vice City,8.41,2.91983,5.49,2.25747,0.47,0.593279
14,Brain Age 2: More Training in Minutes a Day,3.43,2.94415,5.35,2.25269,5.32,0.656384
15,Gran Turismo 3: A-Spec,6.85,2.94415,5.09,2.25269,1.87,0.656384
16,Call of Duty: Modern Warfare 3,9.04,2.76878,4.24,2.13575,0.13,0.410675
17,Call of Duty: Black Ops,9.7,3.34425,3.68,2.49969,0.11,0.508454
18,Call of Duty: Black Ops II,4.99,3.12781,5.73,2.41201,0.65,0.518047
19,Call of Duty: Black Ops II,8.25,3.0243,4.24,2.24052,0.07,0.474379